version: '3'

services:
  nats:
    image: nats:latest
    ports:
      - "4222:4222"  # Client connections
      - "8222:8222"  # HTTP monitoring
      - "6222:6222"  # Clustering
    volumes:
      - nats_data:/data
    restart: unless-stopped
    command: "--jetstream --http_port 8222"
    networks:
      - nats_network

networks:
  nats_network:
    driver: bridge

volumes:
  nats_data: